services:
  - type: web
    name: video-splitter
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn web_app:app
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18